### ISSUE TITLE
Search results do not sort on sample name

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#10]
server: QA 
community: BCM
user: ADMIN

Attempting to sort the Sample Name column. Regardless of the arrow pointing up or down, nothing changes.

On first click I got an "Oops Server Error" message in the upper right.

![screen shot 2017-04-18 at 1 04 16 pm](https://cloud.githubusercontent.com/assets/1234176/25145795/93237468-2437-11e7-9598-483ab6e44dbc.jpg)
![screen shot 2017-04-18 at 1 02 57 pm](https://cloud.githubusercontent.com/assets/1234176/25145796/9323bbd0-2437-11e7-8ed8-632fe0034bc0.jpg)
![screen shot 2017-04-18 at 1 02 50 pm](https://cloud.githubusercontent.com/assets/1234176/25145797/933a3cd4-2437-11e7-88f5-f0a129363845.jpg)

**Comment by kostko** [comment]
Inspected via the API directly and got this error:
> TransportError(400, u'search_phase_execution_exception', u'No mapping found for [name.raw] in order to sort on')

This looks like the indices (more specifically, the `sample_search` index) weren't rebuilt correctly on QA after the last search-related update? cc @tjanez?

**Comment by dblenkus** [comment]
I've rebuild the index manually and it works now. 

Probably the problem is that index rebuild takes quite some time in ansible, so it is common that redeploy is made without rebuilding indexes. 

PR for speed-up of ansible is already prepared (https://github.com/genialis/tower/pull/38), so it shouldn't be a problem in the future.
